finprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('tag/<str:slug>/', views.tag_page),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('search/<str:q>/', views.PostSearch.as_view()),

]

post/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/post/tag/{self.slug}/'
#카테고리
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name


# 상품 아이템
class Post(models.Model):
    name = models.CharField(max_length=30, unique=True)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()
    price = models.IntegerField()

    head_image = models.ImageField(upload_to='post/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='post/images/%Y/%m/%d/', blank=True)


    manufacture = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.name}::{self.manufacture}:{self.price}'

    def get_absolute_url(self):
        return f'/post/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

# 제조사
class Manufacture(models.Model):
    name = models.CharField(max_length=30, unique=True)
    address = models.TextField()
    number = models.IntegerField()

    area = models.TextField()


#댓글 모델?

post/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

post/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Tag, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.

class PostUpdate(LoginRequiredMixin,UpdateView):
    model = Post
    fields = ['name', 'content','price', 'head_image', 'file_upload', 'category'] #, 'tag'
    template_name = 'post/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


    def form_valid(self,form):
        response = super(PostUpdate,self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tag_list = tags_str.split(';')
            for t in tag_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostUpdate,self).get_context_data()
        if self.object.tags.exists:
            tag_str_list = list()
            for t in self.object.tags.all():
                tag_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tag_str_list)
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['name', 'content', 'price', 'head_image', 'file_upload', 'category']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self,form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(PostCreate,self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tag_list = tags_str.split(';')
                for t in tag_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/post/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostCreate,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context

class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList,self).get_context_data()
        context['categories'] =Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context


class PostSearch(PostList): #ListView 상속, post_list, post_list.html
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(Q(title__contains=q) | Q(tags__name__contains=q)).distinct()
        return post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        return context

def new_comment(request,pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk) # 필드명(pk) = 실제 값(pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url()) # redirect = 일을 마치고 전달해주는 페이지?
            else: # GET
                return redirect(post.get_absolute_url())
        else: # 로그인 안한 사용자
            raise PermissionDenied

class CommentUpdate(LoginRequiredMixin,UpdateView):
    # 템플릿 : comment_form
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def category_page(request,slug):
    if slug == 'no_cateogry':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else :
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
    return render(request,'post/post_list.html',{
        'category' : category,
        'post_list' : Post.objects.filter(category=category),
        'categories' : Category.objects.all(),
        'no_category_post_count' : Post.objects.filter(category=None).count
    })


def tag_page(request,slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()
    return render(request, 'post/post_list.html',{
        'tag':tag,
        'post_list':post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })

post/templates/post/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>{% block head_title %}{% endblock %}</title>
    <link href="css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'post/bootstrap4/css/bootstrap.min.css' %}" type="text/css" media="screen">
    <script src="https://kit.fontawesome.com/c99436fad0.js" crossorigin="anonymous"></script>
</head>

<body>
 {% include 'post/navbar.html' %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-9" id="main-area"> <!--왼쪽 부분-->
        {% block main_area %}
        {% endblock %}
      </div>
        <div class="col-md-4 col-lg-3">
          {% include 'post/sidebar.html' %}
        </div>
    </div>
  </div>

 {% include 'post/footer.html' %}


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

post/templates/post/footer.html
<!-- Footer-->
  <footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">@yejincho@gmail.com
      <br>고객센터 02-000-0000   전화번호 010-0000-0000</p></div>
  </footer>

post/templates/post/navbar.html
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#!">Gaeul</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/post/">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#!">마이페이지</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#!">회사소개</a>
                        </li>
                    </ul>

                    <!-- 로그인 유저 -->
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if user.socialaccount_set.all.0.get_avatar_url %}
                                <img class="rounded-circle mr-3" src="{{user.socialaccount_set.all.0.get_avatar_url}}" width="25px" />
                                {% else %}
                                <img class="rounded-circle mr-3" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" width="25px" />
                                {% endif %}
                                {{user.username}}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="/accounts/logout/">LogOut</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">LogIn</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Modal -->
        <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-right-to-bracket"></i> LogIn</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="row">
                    <div class="col-6">
                      <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                        href="/accounts/login/">
                        <i class="fa-regular fa-envelope"></i> LogIn with Email</a>
                    </div>
                    <div class="col-6">
                      <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                        href="/accounts/signup/">
                        <i class="fa-regular fa-envelope"></i>SignUp with Email
                      </a>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
        </div>

post/templates/post/post_detail.html
{% extends 'post/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{post.name}}
{% endblock %}
{% block main_area %}

    <!-- Post content -->
    <div id="post-area">
        <header class="mb-4">
            <!-- Post title -->
            <h1 class="fw-bolder mb-1">{{post.name | lower}}</h1> <!--상품명-->
            {% if post.hook_text %}
            <h5 class="text-muted">{{post.hook_text}}</h5>
            {% endif %}
            <!--categories-->
            {% if post.category %}
            <a class="badge bg-secondary text-decoration-none link-light" href="/post/{{post.category.get_absolute_url}}">
                {{post.category}}
            </a>
            {% else %}
            <a class="badge bg-secondary text-decoration-none link-light" href="/post/category/no_category">
                미분류
            </a>
            {% endif %}
        </header>

        <!-- authenticated-->
        {% if user.is_authenticated and user == post.author %}
            <a class="btn btn-info float-right" href="/post/update_post/{{post.pk}}/" role="button">
                <i class="fas fa-pen">Edit Post</i>
            </a>
        {% endif %}

        <!-- preview image figure -->
        <figure class="mb-4">
            {% if post.head_image %}
            <img class="img-fluid rounded" src="{{post.head_image.url}}" alt="{{post.name}}의 이미지"/>
            {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.pk}}/800/200" alt="random image" />
            {% endif %}
            <br><br>
        </figure>

        <!-- Post content -->
        <div id="comment-area" class="mb-5">
            <p class="fs-5 mb-4">{{post.content}}</p>
            <!-- tags -->
            {% if post.tags.exists %}
            <i class = "fas fa-tag"></i>
            {% for t in post.tags.iterator %}
            <span class="badge badge-pill badge-light">
                <a href="{{t.get_absolute_url}}">
                    {{t}}
                </a>
            </span>
            {% endfor %}
            {% endif %}


            <br><br>
            {% if post.file_upload %}
            <a href="{{post.file_upload.url}}" class="btn btn-outline-dark" role="button" download>
                {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                <i class="fa-regular fa-file-excel"></i>
                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                <i class="fa-regular fa-file-word"></i>
                {% else %}
                <i class="fa-regular fa-file"></i>
                {% endif %}
                Download {{post.get_file_name}}
            </a>
            {% endif %}
        </div>
    </div>

    <!-- Comments section -->
    <section class="mb-5">
        <div class="card bg-light">
            <div class="card-body">
                <!-- Comment form-->  <!--댓글 작성 부분-->
                {% if user.is_authenticated %}
                <form class="mb-4" id="comment-form" method="post" action="{{post.get_absolute_url}}new_comment/">
                    {% csrf_token %}
                    <div class="form-group">
                        {{comment_form | crispy}}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                {% else %}
                    <a role="button" class="btn btn-dark btn-block btn-sm" href="#"
                       data-toggle="modal" data-target="#loginModal">
                        Log in and Leave a comment
                    </a>
                {% endif %}

                {% if post.comment_set.exists %}
                {% for comment in post.comment_set.iterator %}
                <!-- Single comment-->
                <div class="media d-flex" id="comment-{{comment.pk}}">
                    <img class="rounded-circle mr-3" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px" />
                    <div class="media-body ms-3">
                        {% if user.is_authenticated and comment.author == user %}
                        <a role="button" class="btn btn-sm btn-info float-right"
                           href="/blog/update_comment/{{comment.pk}}/">
                            Edit <!-- 댓글 수정 -->
                        </a>
                        {% endif %}
                        <div class="fw-bold">
                            {{comment.author.username}}
                            <small class="text_muted">{{comment.created_at}}</small>
                        </div>
                        <p>{{comment.content | linebreaks}}</p>  <!--linebreaks => 줄바꿈 표시 -->
                        {% if comment.created_at != comment.modified_at %} <!-- comment가 생성된 시간과 업데이트된 시간이 다르다면-->
                        <p class="text-muted float-right">
                            <small>Updated : {{comment.modified_at}} </small>
                        </p>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>





{% endblock %}

post/templates/post/post_form.html
{% extends 'post/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    New Item
{% endblock %}

{% block main_area %}
    <h1>New Item</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form | crispy}}
            <div id="div_id_tags_str">
                <th><label for="id_tags">Tags:</label></th>
                <td><input id="id_tags" type="text" name="tags_str" class="textinput textInput form-control"></td>
            </div>
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

post/templates/post/post_list.html
{% extends 'post/base.html' %}

{% block main_area %}
        {% if user.is_authenticated %}
            {% if user.is_superuser or user.is_staff %}
                <a class="btn btn-info float-right" href="/post/create_post/" role="button">
                    <i class="fas fa-pen"> New Post </i>
                </a>
            {% endif %}
        {% endif %}

<!-- 상품 목록 -->
                <h2>Gaeul
                    {% if search_info %}
                    <span class="badge badge-secondary">{{search_info}}</span>
                    {% endif %}
                    {% if category %}
                    - <span class="badge badge-secondary">{{category}}</span>
                    {% endif %}
                    {% if tag %}
                     - <i class="fas fa_tag"></i>
                    <span class="badge badge-secondary">
                         {{tag}} ({{tag.post_set.count}})
                    </span>
                    {% endif %}
                </h2>
                {% if post_list.exists %}
                {% for p in post_list %}
                <!-- Blog post-->
                <div class="card mb-4" id="post-{{p.pk}}">
                    {% if p.head_image %}
                    <img class="card-img-top" src="{{p.head_image.url}}" alt="{{p}}의 image" /></a>
                    {% else %}
                    <img class="card-img-top" src="https://picsum.photos/seed/{{p.pk}}/800/200" alt="random image" /></a>
                    {% endif %}
                    <div class="card-body">
                        {% if p.category %}
                        <span class="badge badge-secondary float-right">{{p.category}}</span>
                        {% else %}
                        <span class="badge badge-secondary float-right">미분류</span>
                        {% endif %}
                        <h2 class="card-title">{{p.name | upper}}</h2> <!--상품명-->
                        {% if p.hook_text %}
                        <h5 class="text-muted"> {{p.hook_text}} </h5>
                        {% endif %}

                        <p class="card-text">{{p.content | truncatechars:100}}</p>
                        <p class="card-text">{{p.price}}</p>

                        {% if p.tags.exists %}
                        <i class = "fas fa-tag"></i>
                        {% for t in p.tags.iterator %}
                        <span class="badge badge-pill badge-light">
                            <a href="{{t.get_absolute_url}}">
                                {{t}} <!--태그 t를 출력-->
                            </a>
                        </span>
                        {% endfor %}
                        {% endif %}

                        <a class="btn btn-primary" href="{{p.get_absolute_url}}">Read more →</a>
                    </div>
                    <div class="card-footer">
                    <a href="#">{{p.manufacture | upper}}</a> <!--제조사-->
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <h5> 아직 게시물이 없습니다. </h5>
                {% endif %}


                <!-- Pagination-->
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <hr class="my-0" />
                    <ul class="pagination justify-content-center my-4">
                        {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">Newer</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
                        {% endif %}
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Older</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#!">Older</a></li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
{% endblock %}

post/templates/post/post_update_form.html
{% extends 'post/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
  Update Item
{% endblock %}

{% block main_area %}
  <h1>Update Item</h1>
  <hr/>
  <form method="post" enctype="multipart/form-data">
     {% csrf_token %}

        {{form | crispy}}
         <div id="div_id_tags_str">
             <label for="id_tags">Tags:</label>
             <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}"
                    class="textinput textInput form-control">
         </div>

     <button type="submit" class="btn btn-primary float-right">Submit</button>
  </form>
{% endblock %}

post/templates/post/sidebar.html
<!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header"><i class="fa-solid fa-magnifying-glass"></i>Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <script>
                          function searchPost(){
                              let searchValue = document.getElementById('search-input').value.trim();
                              if(searchValue.length > 1){
                                location.href = "/blog/search/" + searchValue +"/";
                              }
                              else{
                                   alert('검색어('+ searchValue +')가 너무 짧아요.');
                              }
                          };
                          document.getElementById('search-input').addEventListener('Keyup', function(event){
                                if(event.key === 'Enter'){
                                    searchPost();
                                }
                          });
                    </script>


                    <!-- Categories widget-->
                    <div class="card mb-4" id='category_card'>
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">

                                    <ul class="list-unstyled mb-0">
                                        {% for c in categories%}
                                        <li><a href="#!">{{c}} ({{c.post_set.count}})</a></li>
                                        {% endfor %}
                                        <li><a href="#!">미분류 ({{no_category_post_count}})</a></li>
                                    </ul>

                            </div>
                        </div>
                    </div>